# to create docker etwrok named roboshop
# since we gave this network as default no need to mention network name in services 
networks:
  default:
    external: true
      name: roboshop
services:
  # Following command is eqalent to docker run -d --name mongodb --netwrok=roboshop mongodb:v1
  mongodb: 
    container_name: mongodb
    image: mongodb:v1
    # networks:
    # - roboshop

  catalogue:
    container_name: catalogue
    image: catalogue:v1
    # since cataloge service need mondodb to work
    depends_on:
    - mongodb

  web:
    container_name: web
    image: web:v1
    # since web has public access we need to give ports
    # frist part of the port is for host and second port is for container
    ports: 
    - "80:80"
    depends_on:
    - catalogue

  redis:
    image: redis

  user:
    container_name: user
    image: user:v1
    depends_on:
    - redis
    - mongodb
  
  cart:
    container_name: cart
    image: cart:v1
    depends_on:
    - redis
    - catalogue
 
  

# docker compose only runs once images are build

# need to be in folder where docker-compose.yaml is to run command

# docker compose up -d  <-- create all the containers mentioned in docker-compose.yaml

# # docker compose  down   <-- to destroy all the containers